# Site wide configuration

title: Eddie Lin  |  Portfolio
description: Data Driven Intelligence
logo: navigation_image/me400x250.png# 120x120 px default image used for Twitter summary card
teaser: navigation_image/electronics400x250.png# 400x250 px default teaser image used in image archive grid
locale:
url:

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
plugins:
  - jekyll-sitemap

# Site owner
owner:
  name: Eddie Lin
  email: tweddielin@gmail.com
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: avatar.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
